FROM golang:1.23.8-alpine AS builder

RUN apk add --no-cache git ca-certificates

WORKDIR /app

COPY go.mod go.sum* ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o migrate migrations/auto.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates postgresql-client
WORKDIR /app

COPY --from=builder /app/migrate .
COPY --from=builder /app/migrations/postgres ./migrations/postgres

CMD ["./migrate", "migrate"]

